import { existsSync } from "fs";
import { mkdir, readFile, rm, writeFile } from "fs/promises";
import { join } from "path";
import {
  captureHookInvocation,
  isAgentUsageStatCommand,
} from "./hook-command.js";
import type { HookConfigurationStatus } from "./hook-status.js";

/**
 * opencode loads every `.js` file in its global plugin directory at startup —
 * verified on opencode 1.18.19 by dropping a bare module there and watching it
 * receive the event stream. That makes the integration a dedicated file we own
 * outright, the same shape as the Copilot hook, with no shared configuration
 * to merge or clobber.
 *
 * The plugin subscribes to `session.idle`, whose payload carries the session id
 * under `event.properties.sessionID`. Idle fires on every quiet point, not only
 * at exit, so a long session checkpoints repeatedly; the shard writer is
 * idempotent and never lowers a recorded value, so extra fires cost nothing.
 */

const MARKER = "AGENT-USAGE-STAT-OPENCODE-PLUGIN-V1";

export async function inspectOpencodeHook(
  pluginPath: string,
): Promise<HookConfigurationStatus> {
  if (!existsSync(pluginPath)) return "missing";
  try {
    const contents = await readFile(pluginPath, "utf-8");
    if (!contents.includes(MARKER)) return "invalid";
    // Recognize the invocation rather than compare it to what this process
    // would generate. Inspection runs from the desktop application and
    // installation from the standalone helper, and the two resolve the helper
    // differently, so an equality check would call every healthy hook stale.
    const invocation = installedInvocation(contents);
    return invocation && isAgentUsageStatCommand(invocation)
      ? "configured"
      : "invalid";
  } catch {
    return "invalid";
  }
}

/** The command line an installed plugin actually spawns, or null. */
function installedInvocation(contents: string): string | null {
  const command = /const COMMAND = ("(?:[^"\\]|\\.)*");/.exec(contents)?.[1];
  const args = /const ARGS = (\[[^\]]*\]);/.exec(contents)?.[1];
  if (!command || !args) return null;
  try {
    return `${JSON.parse(command) as string} ${(JSON.parse(args) as string[]).join(" ")}`;
  } catch {
    return null;
  }
}

/** Write the plugin, replacing any previous version of our own file. */
export async function installOpencodeHook(pluginPath: string): Promise<void> {
  await mkdir(join(pluginPath, ".."), { recursive: true });
  await writeFile(pluginPath, pluginSource(), "utf-8");
}

export async function removeOpencodeHook(pluginPath: string): Promise<void> {
  await rm(pluginPath, { force: true });
}

/**
 * The plugin body.
 *
 * Constraints it must keep: no imports beyond Node built-ins, because opencode
 * loads it without installing anything; no throw that escapes into opencode's
 * event loop, because a plugin fault would degrade the host; and no await on
 * the capture worker, because usage recording must never hold up a session.
 *
 * It writes a hook payload to the worker's stdin exactly as the other hosts
 * do, so opencode capture reaches the same detach shim, the same correlated
 * run protocol, and the same capture-health record.
 */
function pluginSource(): string {
  const { command, args } = captureHookInvocation();
  return `// ${MARKER}
// Generated by Agent Usage Stat. Reinstall from the app rather than editing.
import { spawn } from "node:child_process";

const COMMAND = ${JSON.stringify(command)};
const ARGS = ${JSON.stringify(args)};

export const AgentUsageStat = async ({ directory }) => ({
  event: async ({ event }) => {
    try {
      if (event?.type !== "session.idle") return;
      const sessionId = event?.properties?.sessionID;
      if (!sessionId) return;
      const child = spawn(COMMAND, ARGS, {
        detached: true,
        stdio: ["pipe", "ignore", "ignore"],
        windowsHide: true,
      });
      child.on("error", () => {});
      child.stdin.on("error", () => {});
      child.stdin.end(JSON.stringify({
        hook_event_name: "SessionEnd",
        session_id: sessionId,
        cwd: directory,
      }));
      child.unref();
    } catch {
      // Usage recording is best effort and must never disturb opencode.
    }
  },
});
`;
}
